### ISSUE TITLE
boto3 is unnecessary to import

### ISSUE THREAD

**Issue by infamousjoeg** [cyberark/cyberark-aws-auto-onboarding#7]
When dealing with Python Lambda's in AWS... it is unnecessary to import boto3, since that's already a default package imported and provided by the AWS Lambda environment.

**Comment by zivshits** [comment]
Hi @infamousjoeg,
Thank you for bringing for our attention.
Documentation states https://docs.aws.amazon.com/lambda/latest/dg/lambda-python-how-to-create-deployment-package.html unless you are using specific version of boto3 it is not necessary to import.
We will address this in upcoming release.
